'use client';

import { motion as m } from 'framer-motion';

const motion = {
  div: m.div,
  h1: m.h1,
  h2: m.h2,
  h3: m.h3,
  p: m.p,
  span: m.span,
  button: m.button,
  li: m.li,
  ul: m.ul,
  section: m.section,
  main: m.main,
  nav: m.nav,
  a: m.a,
  img: m.img,
  form: m.form,
  input: m.input,
  textarea: m.textarea,
  select: m.select,
  option: m.option,
  label: m.label,
  article: m.article,
  aside: m.aside,
  footer: m.footer,
  header: m.header,
  figure: m.figure,
  figcaption: m.figcaption,
  blockquote: m.blockquote,
  cite: m.cite,
  code: m.code,
  pre: m.pre,
  strong: m.strong,
  em: m.em,
  small: m.small,
  sub: m.sub,
  sup: m.sup,
  time: m.time,
  mark: m.mark,
  del: m.del,
  ins: m.ins,
  kbd: m.kbd,
  samp: m.samp,
  var: m.var,
  b: m.b,
  i: m.i,
  u: m.u,
  s: m.s,
  q: m.q,
  abbr: m.abbr,
  address: m.address,
  bdo: m.bdo,
  br: m.br,
  caption: m.caption,
  col: m.col,
  colgroup: m.colgroup,
  dd: m.dd,
  dl: m.dl,
  dt: m.dt,
  fieldset: m.fieldset,
  legend: m.legend,
  optgroup: m.optgroup,
  param: m.param,
  progress: m.progress,
  tbody: m.tbody,
  td: m.td,
  tfoot: m.tfoot,
  th: m.th,
  thead: m.thead,
  tr: m.tr,
  wbr: m.wbr
};

export default motion; 